[pytest]
addopts = -v -s --alluredir=allure-results --reruns 1
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: Smoke tests
    ui: UI tests
    constructor: Constructor tests
    order_feed: Order feed tests